### ISSUE TITLE
Installation bug

### ISSUE THREAD

**Issue by ghost** [raspberrypi-ui/piwiz#30]
![install](https://github.com/raspberrypi-ui/piwiz/assets/142316563/54dcc1ea-2761-4042-88e2-4fea16ccb46c)

his setup should give me a Norwegian keyboard layout, I would think? But it does not, it gives me a US layout. No matter if the US keyboard box is ticked or not, it will always give me a US keyboard. Even when the English language box is not ticked, it will give me a US layout.

Also, the Norwegian letter å is shown as a code, in Bokmål. If the Norwegian letter å cannot be shown, then it is standard to use a double aa, like Bokmaal. That would be more correct and look a lot better than what is shown on the screen.

**Comment by spl237** [comment]
The keyboard bug is already fixed in the bookworm release of the startup wizard - I spotted it myself a few weeks ago.

I have also corrected the display of the accented character in the language name both here and in the Raspberry Pi Configuration application, which had the same problem - again, the fix will be in the forthcoming bookworm release.
