### ISSUE TITLE
Don't ask for WiFi credentials if WiFi is already connected.

### ISSUE THREAD

**Issue by DougieLawson** [raspberrypi-ui/piwiz#4]
If I stuff a wpa_supplicant.conf file in /boot before first boot then the startup automation will magically connect to my WiFi network (assuming it's in range and my wpa_supplicant.conf is syntactically correct).

piwiz still asks me for WiFi country code and WiFi credentials.

Please can you check whether WiFi is up and running and associated with an AP before asking for the same credentials you've already got from the "startup magic" that's already happened.

If it's already connected tell me what I'm connected to and ask if I want to leave that alone or change it.

Thanks.

**Comment by spl237** [comment]
Users who are savvy enough to be pre-configuring don't need to use the wizard - just cancel it on the first page. The intention is to provide assistance for absolute beginners booting Raspbian for the first time - the wizard assumes no preconfiguration because a) it is intended only to work in that case and b) because it makes it much simpler to write...

**Comment by ZanderBrown** [comment]
Yeah but they weren't necessarily savvy, perhaps they used a light image of NOOBS.

In such a case they may have connected to WiFi (esp if in PiZeroW) to download the image so NOOBS will have preconfigured WiFi based on the connection

**Comment by DougieLawson** [comment]
It's not difficult to discover if you're connected. exec('iwgetid -r') and parse the results.

Or write your own code to sniff out the SSID.
```
#include "iwlib.h"              /* Header */
static int
print_essid(int                 skfd,
            const char *        ifname)
{
  struct iwreq          wrq;
  char                  essid[IW_ESSID_MAX_SIZE + 1];   /* ESSID */
  unsigned int          i;
  unsigned int          j;

  /* Make sure ESSID is always NULL terminated */
  memset(essid, 0, sizeof(essid));

  /* Get ESSID */
  wrq.u.essid.pointer = (caddr_t) essid;
  wrq.u.essid.length = IW_ESSID_MAX_SIZE + 1;
  wrq.u.essid.flags = 0;
  if(iw_get_ext(skfd, ifname, SIOCGIWESSID, &wrq) < 0)
    return(-1);

  printf("%s\n", essid);

  return(0);
}

static int
print_one_device(int            skfd,
                 const char*    ifname)
{
  int ret;
  ret = print_essid(skfd, ifname);
  return(ret);
}
static int
scan_devices(int                skfd)
{
  char          buff[1024];
  struct ifconf ifc;
  struct ifreq *ifr;
  int           i;

  /* Get list of active devices */
  ifc.ifc_len = sizeof(buff);
  ifc.ifc_buf = buff;
  if(ioctl(skfd, SIOCGIFCONF, &ifc) < 0)
    {
      perror("SIOCGIFCONF");
      return(-1);
    }
  ifr = ifc.ifc_req;

  /* Print the first match */
  for(i = ifc.ifc_len / sizeof(struct ifreq); --i >= 0; ifr++)
    {
      if(print_one_device(skfd, ifr->ifr_name) >= 0)
        return 0;
    }
  return(-1);
}
int
main(int        argc,
     char **    argv)
{
  int   skfd;                   /* generic raw socket desc.     */
  int   opt;
  int   ret = -1;

  if((skfd = iw_sockets_open()) < 0)
    {
      perror("socket");
      return(-1);
    }
      ret = scan_devices(skfd);

  fflush(stdout);
  iw_sockets_close(skfd);
  return(ret);
}
```

It's no good burying your head in the sand because you think [or know] that I'm an expert user and know how to avoid the problem. Make things simple for the less sophisticated users who may have found the wpa_supplicant.conf magic.

**Comment by spl237** [comment]
I know full well how to establish the SSID of the connected network, as I already do it in the networking plugin to show the connected network in the menu (and it requires rather less code than you show above, as the wizard is using the same interface to dhcpcd as the networking plugin). But it is covering what is at best a corner case - I have a lot to do and a limited amount of time, and adding functionality which will be exercised as seldom as this is not a constructive use thereof. I repeat - the wizard is to configure clean images; the use case you describe is uncommon, to say the least.

**Comment by ZanderBrown** [comment]
So the official 'OS installer' (NOOBS) installing the official 'clean' Raspbian image over WiFi is an uncommon, unsupported, use case?

> I know full well how to establish the SSID of the connected network

Is a bit rude really, I'm sure @DougieLawson never intended any insult and is only trying to help here

I know your very busy but you often seem to come across quite hostile, rpi is a community and the community it trying to help but you often shut people down immediately. I'm sure @DougieLawson, myself or someone else would happily implement this if you don't have the time but there is little point in any of us putting the work in when it's seems quite likely any PR will be rejected

(Yes I know some PRs/Issues are 'stupid' and I'm responsible for a couple of them)

**Comment by spl237** [comment]
> So the official 'OS installer' (NOOBS) installing the official 'clean' Raspbian image over WiFi is an uncommon, unsupported, use case?

The use of the light version of NOOBS to install Raspbian _is_ an uncommon use case - the light version is to enable people to install _other_ OSes without the overhead of downloading Raspbian. If someone wants to install Raspbian, 99 times out of 100 they will download the full version of NOOBS which already includes it, and therefore have no need of a wi-fi connection within it.

If someone has already got a wi-fi connection when the wizard runs, nothing breaks - everything works. They can just press Skip on the wi-fi connection screen, or cancel the wizard completely. Given the number of people affected (minimal) and the actual adverse effect on those people (non-existent), I'm sorry, but I do not see this as a major problem requiring a fix.

For what it's worth, I have already considered modifying the wizard to load pre-existing wireless config, but it is actually potentially confusing, due to the use of a selection tool (a list box) being used to show pre-existing status rather than being used to show a selection the user is being asked to make. The code already exists to do this - it's a one-line change - but I have not yet decided whether enabling it is actually more trouble than it is worth.
